import type { MonthlyCostOverview } from "@/types/cost";

export const monthlyCostOverview: MonthlyCostOverview = {
  month: "2026-08",
  reportingCurrency: "JPY",
  services: [
    {
      service: "openai",
      displayName: "OpenAI",
      currency: "JPY",
      currentMonthCost: 0,
      estimatedCost: null,
      usageSummary: [{ label: "API使用量", value: 0, unit: "未入力" }],
      freeTierSummary: "手入力前のため未確認",
      dataSource: "api-ready",
      updatedAt: "2026-08-01T00:00:00.000Z",
      notes: "Phase 1B manual fixture。実際の請求額は未入力です。",
      includedInTotal: true,
    },
    {
      service: "google-cloud",
      displayName: "Google Cloud",
      currency: "JPY",
      currentMonthCost: 0,
      estimatedCost: null,
      usageSummary: [{ label: "クラウド使用量", value: 0, unit: "未入力" }],
      freeTierSummary: "手入力前のため未確認",
      dataSource: "future-api",
      updatedAt: "2026-08-01T00:00:00.000Z",
      notes:
        "Phase 1B manual fixture。Firestoreを含む請求総額の入力先です。",
      includedInTotal: true,
    },
    {
      service: "firebase",
      displayName: "Firebase / Firestore",
      currency: "JPY",
      currentMonthCost: 0,
      estimatedCost: null,
      usageSummary: [
        { label: "Firestore読み取り", value: 0, unit: "未入力" },
        { label: "Firestore書き込み", value: 0, unit: "未入力" },
      ],
      freeTierSummary: "Sparkプラン無料枠の使用状況は未入力",
      dataSource: "manual",
      updatedAt: "2026-08-01T00:00:00.000Z",
      notes:
        "Firebaseの請求額はGoogle Cloud側に含まれるため、今月合計には二重加算しません。",
      includedInTotal: false,
    },
    {
      service: "github",
      displayName: "GitHub",
      currency: "JPY",
      currentMonthCost: 0,
      estimatedCost: null,
      usageSummary: [{ label: "利用状況", value: 0, unit: "未入力" }],
      freeTierSummary: "手入力前のため未確認",
      dataSource: "manual",
      updatedAt: "2026-08-01T00:00:00.000Z",
      notes: "Phase 1B manual fixture。実際の請求額は未入力です。",
      includedInTotal: true,
    },
    {
      service: "vercel",
      displayName: "Vercel",
      currency: "JPY",
      currentMonthCost: 0,
      estimatedCost: null,
      usageSummary: [{ label: "利用状況", value: 0, unit: "未入力" }],
      freeTierSummary: "手入力前のため未確認",
      dataSource: "manual",
      updatedAt: "2026-08-01T00:00:00.000Z",
      notes: "Phase 1B manual fixture。実際の請求額は未入力です。",
      includedInTotal: true,
    },
  ],
};
